//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebApplication6.WSCate {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
        using Entidades;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSCategoriasSoap", Namespace="http://tempuri.org/")]
    public partial class WSCategorias : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback InsertarOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertarProOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarProductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarProductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarCateOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarCateOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSCategorias() {
            this.Url = global::WebApplication6.Properties.Settings.Default.WebApplication6_WSCate_WSCategorias;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event InsertarCompletedEventHandler InsertarCompleted;
        
        /// <remarks/>
        public event InsertarProCompletedEventHandler InsertarProCompleted;
        
        /// <remarks/>
        public event ModificarProductoCompletedEventHandler ModificarProductoCompleted;
        
        /// <remarks/>
        public event EliminarProductoCompletedEventHandler EliminarProductoCompleted;
        
        /// <remarks/>
        public event ModificarCateCompletedEventHandler ModificarCateCompleted;
        
        /// <remarks/>
        public event EliminarCateCompletedEventHandler EliminarCateCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Insertar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Insertar(Categoria cate) {
            object[] results = this.Invoke("Insertar", new object[] {
                        cate});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void InsertarAsync(Categoria cate) {
            this.InsertarAsync(cate, null);
        }
        
        /// <remarks/>
        public void InsertarAsync(Categoria cate, object userState) {
            if ((this.InsertarOperationCompleted == null)) {
                this.InsertarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertarOperationCompleted);
            }
            this.InvokeAsync("Insertar", new object[] {
                        cate}, this.InsertarOperationCompleted, userState);
        }
        
        private void OnInsertarOperationCompleted(object arg) {
            if ((this.InsertarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertarCompleted(this, new InsertarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertarPro", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int InsertarPro(Productos pro) {
            object[] results = this.Invoke("InsertarPro", new object[] {
                        pro});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void InsertarProAsync(Productos pro) {
            this.InsertarProAsync(pro, null);
        }
        
        /// <remarks/>
        public void InsertarProAsync(Productos pro, object userState) {
            if ((this.InsertarProOperationCompleted == null)) {
                this.InsertarProOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertarProOperationCompleted);
            }
            this.InvokeAsync("InsertarPro", new object[] {
                        pro}, this.InsertarProOperationCompleted, userState);
        }
        
        private void OnInsertarProOperationCompleted(object arg) {
            if ((this.InsertarProCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertarProCompleted(this, new InsertarProCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModificarProducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ModificarProducto(Productos pro) {
            object[] results = this.Invoke("ModificarProducto", new object[] {
                        pro});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ModificarProductoAsync(Productos pro) {
            this.ModificarProductoAsync(pro, null);
        }
        
        /// <remarks/>
        public void ModificarProductoAsync(Productos pro, object userState) {
            if ((this.ModificarProductoOperationCompleted == null)) {
                this.ModificarProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarProductoOperationCompleted);
            }
            this.InvokeAsync("ModificarProducto", new object[] {
                        pro}, this.ModificarProductoOperationCompleted, userState);
        }
        
        private void OnModificarProductoOperationCompleted(object arg) {
            if ((this.ModificarProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarProductoCompleted(this, new ModificarProductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarProducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int EliminarProducto(Productos pro) {
            object[] results = this.Invoke("EliminarProducto", new object[] {
                        pro});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void EliminarProductoAsync(Productos pro) {
            this.EliminarProductoAsync(pro, null);
        }
        
        /// <remarks/>
        public void EliminarProductoAsync(Productos pro, object userState) {
            if ((this.EliminarProductoOperationCompleted == null)) {
                this.EliminarProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarProductoOperationCompleted);
            }
            this.InvokeAsync("EliminarProducto", new object[] {
                        pro}, this.EliminarProductoOperationCompleted, userState);
        }
        
        private void OnEliminarProductoOperationCompleted(object arg) {
            if ((this.EliminarProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarProductoCompleted(this, new EliminarProductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModificarCate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ModificarCate(Categoria cat) {
            object[] results = this.Invoke("ModificarCate", new object[] {
                        cat});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ModificarCateAsync(Categoria cat) {
            this.ModificarCateAsync(cat, null);
        }
        
        /// <remarks/>
        public void ModificarCateAsync(Categoria cat, object userState) {
            if ((this.ModificarCateOperationCompleted == null)) {
                this.ModificarCateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarCateOperationCompleted);
            }
            this.InvokeAsync("ModificarCate", new object[] {
                        cat}, this.ModificarCateOperationCompleted, userState);
        }
        
        private void OnModificarCateOperationCompleted(object arg) {
            if ((this.ModificarCateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarCateCompleted(this, new ModificarCateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarCate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int EliminarCate(Categoria cat) {
            object[] results = this.Invoke("EliminarCate", new object[] {
                        cat});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void EliminarCateAsync(Categoria cat) {
            this.EliminarCateAsync(cat, null);
        }
        
        /// <remarks/>
        public void EliminarCateAsync(Categoria cat, object userState) {
            if ((this.EliminarCateOperationCompleted == null)) {
                this.EliminarCateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarCateOperationCompleted);
            }
            this.InvokeAsync("EliminarCate", new object[] {
                        cat}, this.EliminarCateOperationCompleted, userState);
        }
        
        private void OnEliminarCateOperationCompleted(object arg) {
            if ((this.EliminarCateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarCateCompleted(this, new EliminarCateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Categoria1 {
        
        private string tipoField;
        
        private int id_categoriaField;
        
        private string tipoField1;
        
        private int idCategoriaField;
        
        /// <remarks/>
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        public int id_categoria {
            get {
                return this.id_categoriaField;
            }
            set {
                this.id_categoriaField = value;
            }
        }
        
        /// <remarks/>
        public string Tipo {
            get {
                return this.tipoField1;
            }
            set {
                this.tipoField1 = value;
            }
        }
        
        /// <remarks/>
        public int IdCategoria {
            get {
                return this.idCategoriaField;
            }
            set {
                this.idCategoriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Productos1 {
        
        private string descripcionField;
        
        private int id_categoriaField;
        
        private int id_productoField;
        
        private string descripcionField1;
        
        private int id_CategoriaField;
        
        private int idField;
        
        /// <remarks/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public int id_categoria {
            get {
                return this.id_categoriaField;
            }
            set {
                this.id_categoriaField = value;
            }
        }
        
        /// <remarks/>
        public int id_producto {
            get {
                return this.id_productoField;
            }
            set {
                this.id_productoField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField1;
            }
            set {
                this.descripcionField1 = value;
            }
        }
        
        /// <remarks/>
        public int Id_Categoria {
            get {
                return this.id_CategoriaField;
            }
            set {
                this.id_CategoriaField = value;
            }
        }
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void InsertarCompletedEventHandler(object sender, InsertarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void InsertarProCompletedEventHandler(object sender, InsertarProCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertarProCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertarProCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ModificarProductoCompletedEventHandler(object sender, ModificarProductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ModificarProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ModificarProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void EliminarProductoCompletedEventHandler(object sender, EliminarProductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ModificarCateCompletedEventHandler(object sender, ModificarCateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ModificarCateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ModificarCateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void EliminarCateCompletedEventHandler(object sender, EliminarCateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarCateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarCateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591